# Pandas Series and DataFrame

In [2]:
import numpy as np
import pandas as pd

---
# 1. Series

Series是pandas中暴露给我们使用的基本对象，它是由相同元素类型构成的一维数据结构，同时具有列表和字典的属性（字典的属性由索引赋予）。

    Series：有序，有索引
    list：  有序，无索引
    dict：  无序，有索引

## 1.1 预览

In [3]:
data = [1, 2, 3]
index = ['a', 'b', 'c']
s = pd.Series(data=data, index=index, name = 'sss')
s

a    1
b    2
c    3
Name: sss, dtype: int64

In [3]:
s.index  # 四个属性之一：索引

Index(['a', 'b', 'c'], dtype='object')

In [4]:
s.name  # 四个属性之二：名字

'sss'

In [5]:
s.values # 四个属性之三：值

array([1, 2, 3])

In [6]:
s.dtype # 四个属性之四：元素类型

dtype('int64')

----
## 1.2 创建

#### `pd.Series(data=None, index=None, name = None)`
- data：多种类型，见下面具体介绍
- index：索引
- name：对data的说明，用的不多，一般在和DataFrame、Index互相转换时才需要。

### 1.2.1 data无索引
- 如果 data 为 **ndarray(1D) 或 list(1D)**，那么其缺少 Series 需要的索引信息；
- 如果提供 index，如果给定则必须和data长度相同；
- 如果不提供 index，那么其将生成默认数值索引 range(0, data.shape[0])。

In [7]:
# data = [1,2,3]
data1 = np.array([1,2,3])
index1 = ['a','b','c']
s = pd.Series(data = data1, index = index1)
s

a    1
b    2
c    3
dtype: int64

### 1.2.2 data有索引
 - 如果 data 为 **Series 或 dict** ，那么其已经提供了 Series 需要的索引信息，所以 index 项是不需要提供的；
 - 如果额外提供了 index 项，那么其将对当前构建的Series进行 重索引（增删）（等同于reindex操作）。

In [8]:
# data = pd.Series([a,b,c], index = ['a','b','c'] )
data2 = { 'a':1, 'b':2,'c':3 }
index2 = ['a','b','d']
s = pd.Series(data = data2, index = index2)
s

a    1.0
b    2.0
d    NaN
dtype: float64

#### 如上，index项用于从当前已有索引中匹配出相同的行，如果当前索引缺失给定的索引，则填充NaN（NaN：not a number为pandas缺失值标记）。

----
# 2. DataFrame
DataFrame由具有共同索引的Series按列排列构成（2D），是使用最多的对象。

ps:
  存在拓展到 3D 的数据结构 pd.Panel

## 2.1 预览

In [9]:
data = [[1,2,3],
       [4,5,6]]
index = ['a','b']
columns = ['A','B','C']
df = pd.DataFrame(data=data, index = index, columns = columns)
df

A  B  C
a  1  2  3
b  4  5  6

In [10]:
df.index  # 行索引

Index(['a', 'b'], dtype='object')

In [11]:
df.columns  # 列索引，与Series的name一个意思

Index(['A', 'B', 'C'], dtype='object')

In [12]:
df.values 

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
df.dtypes  # 这里的dtype带s，查看每列元素类型

A    int64
B    int64
C    int64
dtype: object

----
## 2.2 创建
#### `pd.DataFrame(data=None, index=None, columns=None)`
函数由多个参数，对我们有用的主要是：`data`,`index`和`columns`三项

### 2.1 data无 行索引，无 列索引
- 如果 data 为 **ndarray(2D) or list(2D)**，那么其缺少 DataFrame 需要的行、列索引信息；
- 如果提供 index 或 columns 项，其必须和data的行 或 列长度相同；
- 如果不提供 index 或 columns 项，那么其将默认生成数值索引range(0, data.shape[0])) 或 range(0, data.shape[1])。

In [14]:
# data = [[1,2,3],
#        [4,5,6]]
data1 = np.array([[1,2,3],
                [4,5,6]] )
index1 = ['a','b']
columns1 = ['A','B','C']
df = pd.DataFrame(data=data1, index = index1, columns = columns1)
df

A  B  C
a  1  2  3
b  4  5  6

### 2.2 data无 行索引，有 列索引
 - 如果data为 **dict of ndarray(1D) or list(1D)**，所有ndarray或list的长度必须相同。且dict的key为DataFrame提供了需要的columns信息，缺失index；
 - 如果提供 index 项，必须和list的长度相同；
 - 如果不提供 index，那么其将默认生成数值索引range(0, data.shape[0]))；
 - 如果还额外提供了columns项，那么其将对当前构建的DataFrame进行 **列重索引**。

In [15]:
data2 = { 'A' : [1,4], 'B': [2,5], 'C':[3,6] }
index2 = ['a','b']
columns2 = ['A','B','D']
df = pd.DataFrame(data=data2, index = index2, columns = columns2)
df

A  B    D
a  1  2  NaN
b  4  5  NaN

### 2.3 data有 行索引，有 列索引
 - 如果data为 **dict of Series or dict**，那么其已经提供了DataFrame需要的所有信息；
 - 如果多个Series或dict间的索引不一致，那么取并操作（pandas不会试图丢掉信息），缺失的数据填充NaN；
 - 如果提供了index项或columns项，那么其将对当前构建的DataFrame进行 重索引（reindex，pandas内部调用接口）。

In [5]:
# data3 = { 'A' : pd.Series([1,4] ,index = ['a','b']), 'B' : pd.Series([2,5] ,index = ['a','b']), 'C' : pd.Series([3,6] ,index = ['a','c']) }
data3 = { 'A' : { 'a':1, 'b':4}, 'B': {'a':2,'b':5}, 'C':{'a':3, 'c':6}, 'D': {'a': 3, 'd': 10}}
df = pd.DataFrame(data=data3)
df

A    B    C     D
a  1.0  2.0  3.0   3.0
b  4.0  5.0  NaN   NaN
c  NaN  NaN  6.0   NaN
d  NaN  NaN  NaN  10.0

---
# 3. 文件读写／数据库读写

#### `pd.read_csv(filepath_or_buffer, sep=',', header='infer', names=None,index_col=None, encoding=None ) `
read_csv的参数很多，但这几个参数就够我们使用了：
- filepath_or_buffer：路径和文件名不要带中文，带中文容易报错。
- sep: csv文件数据的分隔符，默认是','，根据实际情况修改；
- header：如果有列名，那么这一项不用改；
- names：如果没有列名，那么必须设置header = None， names为列名的列表，不设置默认生成数值索引；
- index_col：int型，选取这一列作为索引。
- encoding：根据你的文档编码来确定，如果有中文读取报错，试试encoding = 'gbk'。


#### `pd.read_excel(io, sheetname=0, header=0, index_col=None, names=None) `
read_excel的参数很多，但这几个参数就够我们使用了：
- header：如果有列名，那么这一项不用改；
- names：如果没有列名，那么必须设置header = None， names为列名的列表，不设置默认生成数值索引；
- index_col：int型，选取这一列作为索引。


#### `pd.read_sql`

#### `pd.read_table`

#### `pd.to_sql`

#### `pd.to_csv`

In [17]:
help(pd.DataFrame.to_csv)

Help on function to_csv in module pandas.core.frame:

to_csv(self, path_or_buf=None, sep=',', na_rep='', float_format=None, columns=None, header=True, index=True, index_label=None, mode='w', encoding=None, compression=None, quoting=None, quotechar='"', line_terminator='\n', chunksize=None, tupleize_cols=False, date_format=None, doublequote=True, escapechar=None, decimal='.')
    Write DataFrame to a comma-separated values (csv) file
    
    Parameters
    ----------
    path_or_buf : string or file handle, default None
        File path or object, if None is provided the result is returned as
        a string.
    sep : character, default ','
        Field delimiter for the output file.
    na_rep : string, default ''
        Missing data representation
    float_format : string, default None
        Format string for floating point numbers
    columns : sequence, optional
        Columns to write
    header : boolean or list of string, default True
        Write out column names. If 

#### `pd.to_excel`

In [18]:
help(pd.DataFrame.to_excel)

Help on function to_excel in module pandas.core.frame:

to_excel(self, excel_writer, sheet_name='Sheet1', na_rep='', float_format=None, columns=None, header=True, index=True, index_label=None, startrow=0, startcol=0, engine=None, merge_cells=True, encoding=None, inf_rep='inf', verbose=True, freeze_panes=None)
    Write DataFrame to an excel sheet
    
    
    Parameters
    ----------
    excel_writer : string or ExcelWriter object
        File path or existing ExcelWriter
    sheet_name : string, default 'Sheet1'
        Name of sheet which will contain DataFrame
    na_rep : string, default ''
        Missing data representation
    float_format : string, default None
        Format string for floating point numbers
    columns : sequence, optional
        Columns to write
    header : boolean or list of string, default True
        Write out column names. If a list of string is given it is
        assumed to be aliases for the column names
    index : boolean, default True
        

In [7]:
tips = pd.read_csv( 'tips.csv')

In [ ]:
tips.

In [12]:
tips.sample(10)

total_bill    tip     sex smoker   day    time  size
154       19.77   2.00    Male     No   Sun  Dinner     4
50        12.54   2.50    Male     No   Sun  Dinner     2
103       22.42   3.48  Female    Yes   Sat  Dinner     2
170       50.81  10.00    Male    Yes   Sat  Dinner     3
234       15.53   3.00    Male    Yes   Sat  Dinner     2
133       12.26   2.00  Female     No  Thur   Lunch     2
4         24.59   3.61  Female     No   Sun  Dinner     4
40        16.04   2.24    Male     No   Sat  Dinner     3
33        20.69   2.45  Female     No   Sat  Dinner     4
37        16.93   3.07  Female     No   Sat  Dinner     3

In [20]:
tips.index

RangeIndex(start=0, stop=244, step=1)

In [21]:
tips.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [22]:
tips.values

array([[16.99, 1.01, 'Female', ..., 'Sun', 'Dinner', 2],
       [10.34, 1.66, 'Male', ..., 'Sun', 'Dinner', 3],
       [21.01, 3.5, 'Male', ..., 'Sun', 'Dinner', 3],
       ..., 
       [22.67, 2.0, 'Male', ..., 'Sat', 'Dinner', 2],
       [17.82, 1.75, 'Male', ..., 'Sat', 'Dinner', 2],
       [18.78, 3.0, 'Female', ..., 'Thur', 'Dinner', 2]], dtype=object)

In [13]:
# output
tips.to_csv('tips_out.csv')
tips.to_excel('tips_out.xlsx')

In [15]:
# save to sqllite

import sqlite3
from sqlalchemy import create_engine

In [16]:
conn = sqlite3.connect("demo.db")

In [50]:
try:
    tips.to_sql(con=conn,
                name='tips', 
                if_exists='fail')
except Exception as exc:
    print(exc)

Table 'tips' already exists.


In [51]:
## reading sql

In [17]:
tips_db = pd.read_sql(con=conn, sql='select * from tips')
tips_db

index  total_bill   tip     sex smoker   day    time  size
0        0       16.99  1.01  Female     No   Sun  Dinner     2
1        1       10.34  1.66    Male     No   Sun  Dinner     3
2        2       21.01  3.50    Male     No   Sun  Dinner     3
3        3       23.68  3.31    Male     No   Sun  Dinner     2
4        4       24.59  3.61  Female     No   Sun  Dinner     4
5        5       25.29  4.71    Male     No   Sun  Dinner     4
6        6        8.77  2.00    Male     No   Sun  Dinner     2
7        7       26.88  3.12    Male     No   Sun  Dinner     4
8        8       15.04  1.96    Male     No   Sun  Dinner     2
9        9       14.78  3.23    Male     No   Sun  Dinner     2
10      10       10.27  1.71    Male     No   Sun  Dinner     2
11      11       35.26  5.00  Female     No   Sun  Dinner     4
12      12       15.42  1.57    Male     No   Sun  Dinner     2
13      13       18.43  3.00    Male     No   Sun  Dinner     4
14      14       14.83  3.02  Female     No   Sun  Dinner     2
15      15       21.58  3.92    Male     No   Sun  Dinner     2
16      16       10.33  1.67  Female     No   Sun  Dinner     3
17      17       16.29  3.71    Male     No   Sun  Dinner     3
18      18       16.97  3.50  Female     No   Sun  Dinner     3
19      19       20.65  3.35    Male     No   Sat  Dinner     3
20      20       17.92  4.08    Male     No   Sat  Dinner     2
21      21       20.29  2.75  Female     No   Sat  Dinner     2
22      22       15.77  2.23  Female     No   Sat  Dinner     2
23      23       39.42  7.58    Male     No   Sat  Dinner     4
24      24       19.82  3.18    Male     No   Sat  Dinner     2
25      25       17.81  2.34    Male     No   Sat  Dinner     4
26      26       13.37  2.00    Male     No   Sat  Dinner     2
27      27       12.69  2.00    Male     No   Sat  Dinner     2
28      28       21.70  4.30    Male     No   Sat  Dinner     2
29      29       19.65  3.00  Female     No   Sat  Dinner     2
..     ...         ...   ...     ...    ...   ...     ...   ...
214    214       28.17  6.50  Female    Yes   Sat  Dinner     3
215    215       12.90  1.10  Female    Yes   Sat  Dinner     2
216    216       28.15  3.00    Male    Yes   Sat  Dinner     5
217    217       11.59  1.50    Male    Yes   Sat  Dinner     2
218    218        7.74  1.44    Male    Yes   Sat  Dinner     2
219    219       30.14  3.09  Female    Yes   Sat  Dinner     4
220    220       12.16  2.20    Male    Yes   Fri   Lunch     2
221    221       13.42  3.48  Female    Yes   Fri   Lunch     2
222    222        8.58  1.92    Male    Yes   Fri   Lunch     1
223    223       15.98  3.00  Female     No   Fri   Lunch     3
224    224       13.42  1.58    Male    Yes   Fri   Lunch     2
225    225       16.27  2.50  Female    Yes   Fri   Lunch     2
226    226       10.09  2.00  Female    Yes   Fri   Lunch     2
227    227       20.45  3.00    Male     No   Sat  Dinner     4
228    228       13.28  2.72    Male     No   Sat  Dinner     2
229    229       22.12  2.88  Female    Yes   Sat  Dinner     2
230    230       24.01  2.00    Male    Yes   Sat  Dinner     4
231    231       15.69  3.00    Male    Yes   Sat  Dinner     3
232    232       11.61  3.39    Male     No   Sat  Dinner     2
233    233       10.77  1.47    Male     No   Sat  Dinner     2
234    234       15.53  3.00    Male    Yes   Sat  Dinner     2
235    235       10.07  1.25    Male     No   Sat  Dinner     2
236    236       12.60  1.00    Male    Yes   Sat  Dinner     2
237    237       32.83  1.17    Male    Yes   Sat  Dinner     2
238    238       35.83  4.67  Female     No   Sat  Dinner     3
239    239       29.03  5.92    Male     No   Sat  Dinner     3
240    240       27.18  2.00  Female    Yes   Sat  Dinner     2
241    241       22.67  2.00    Male    Yes   Sat  Dinner     2
242    242       17.82  1.75    Male     No   Sat  Dinner     2
243    243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 8 columns]

In [53]:
tips_db = pd.read_sql_query(con=conn, sql='select * from tips limit 5')
tips_db

index  total_bill   tip     sex smoker  day    time  size
0      0       16.99  1.01  Female     No  Sun  Dinner     2
1      1       10.34  1.66    Male     No  Sun  Dinner     3
2      2       21.01  3.50    Male     No  Sun  Dinner     3
3      3       23.68  3.31    Male     No  Sun  Dinner     2
4      4       24.59  3.61  Female     No  Sun  Dinner     4

In [20]:
tips_index = tips.set_index(['sex', 'smoker'])